apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
        - name: mywebsite-container
          image: ramjogesh/mywebsite:${BUILD_NUMBER}
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  type: NodePort
  selector:
    app: mywebsite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008

